/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetosenac.TELAS;

import com.mycompany.projetosenac.persistencia.ServicosJPA;
import com.mycompany.projetosenac.persistencia.TiposServicos;
import com.mycompany.projetosenac.persistencia.User;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class PetShopServicos extends javax.swing.JFrame {

    /**
     * Creates new form PetShopServicos
     */
    public PetShopServicos(User u) {
        initComponents();

        if (u.getCargo().equalsIgnoreCase("Gerente")) {
            jButtonNovo.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonLOGIN.setEnabled(true);
            jButtonCDPET.setEnabled(true);
            jButtonCDTUTOR.setEnabled(true);
        } else if (u.getCargo().equalsIgnoreCase("Atendente")) {
            jButtonExcluir.setEnabled(false);
            jButtonLOGIN.setEnabled(true);
            jButtonCDPET.setEnabled(true);
            jButtonCDTUTOR.setEnabled(true);
            jButtonNovo.setEnabled(true);

        } else {
            jButtonNovo.setEnabled(false);
            jButtonExcluir.setEnabled(false);
            jButtonLOGIN.setEnabled(false);
            jButtonCDPET.setEnabled(false);
            jButtonCDTUTOR.setEnabled(false);
        }
    }

    public PetShopServicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldBuscarP = new javax.swing.JTextField();
        jTextFielPesquisar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCDPET = new javax.swing.JButton();
        jButtonCDTUTOR = new javax.swing.JButton();
        jButtonLOGIN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableServicos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pesquisar por pet :");

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("         LISTA DE SERVIÇOS");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFielPesquisar2.setText("Pesquisar");
        jTextFielPesquisar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFielPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielPesquisar2ActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo +");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCDPET.setText("Cadastrar PET");
        jButtonCDPET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCDPETActionPerformed(evt);
            }
        });

        jButtonCDTUTOR.setText("Cadastrar TUTOR");
        jButtonCDTUTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCDTUTORActionPerformed(evt);
            }
        });

        jButtonLOGIN.setBackground(new java.awt.Color(204, 0, 0));
        jButtonLOGIN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLOGIN.setText("LOGIN");
        jButtonLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLOGINActionPerformed(evt);
            }
        });

        jTableServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "TutorRes", "Horario"
            }
        ));
        jScrollPane2.setViewportView(jTableServicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(27, 27, 27)
                                        .addComponent(jButtonLOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonCDTUTOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonCDPET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFielPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFielPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonNovo)
                                    .addComponent(jButtonCDPET))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonExcluir)
                                    .addComponent(jButtonCDTUTOR)))
                            .addComponent(jButtonLOGIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFielPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielPesquisar2ActionPerformed
        List<TiposServicos> lista = ServicosJPA.buscar(jTextFieldBuscarP.getText());
        DefaultTableModel tabela = montarTabela(lista);
        jTableServicos.setModel(tabela);
        jScrollPane2.setViewportView(jTableServicos);

    }//GEN-LAST:event_jTextFielPesquisar2ActionPerformed

    private void jButtonCDTUTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCDTUTORActionPerformed
        CadastroTUTOR tela = new CadastroTUTOR();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCDTUTORActionPerformed

    private void jButtonCDPETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCDPETActionPerformed
        CadastroPETS tela = new CadastroPETS();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonCDPETActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        Servicos tela = new Servicos();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLOGINActionPerformed
        PetShopLogin tela = new PetShopLogin();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonLOGINActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        try {
            int linhaSelecionada = jTableServicos.getSelectedRow();

            if (linhaSelecionada >= 0) {
                // Suponha que a coluna 1 seja o campo "tipo"
                String tipo = jTableServicos.getValueAt(linhaSelecionada, 1).toString();

                int resposta = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o serviço com tipo: " + tipo + "?");

                if (resposta == 0) {
                    ServicosJPA servicosJPA = new ServicosJPA();

                    // Excluir pelo valor da coluna "tipo"
                    ServicosJPA.excluirPorTipo(tipo);

                    JOptionPane.showMessageDialog(this, "Registro excluído com sucesso");

                    jTextFielPesquisar2ActionPerformed(evt); 
                }
            }

            jTableServicos.setModel(montarTabela(ServicosJPA.listar()));
            jScrollPane2.setViewportView(jTableServicos);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
        }
    


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jTableServicos.setModel(montarTabela(ServicosJPA.listar()));
        jScrollPane2.setViewportView(jTableServicos);
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetShopServicos.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetShopServicos.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetShopServicos.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetShopServicos.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetShopServicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCDPET;
    private javax.swing.JButton jButtonCDTUTOR;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLOGIN;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableServicos;
    private javax.swing.JButton jTextFielPesquisar2;
    private javax.swing.JTextField jTextFieldBuscarP;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel montarTabela(List<TiposServicos> listar) {
        DefaultTableModel tabela = new DefaultTableModel();
        tabela.setColumnIdentifiers(new String[]{"tipo", "tutorRes", "horario"});

        if (listar != null) {
            for (TiposServicos l : listar) {
                tabela.addRow(new Object[]{
                    l.gettipo(),
                    l.gettutorRes(),
                    l.gethorario()
                });

            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum serviço encontrado!!");
        }
        return tabela;
    }

}
